version: "3.8"
services:
  # services
  homeassistant:
    image: homeassistant/home-assistant:stable
    container_name: homeassistant
    restart: unless-stopped
    network_mode: host
    environment:
      TZ: '{{ timezone }}'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - '{{ root_path }}/home-assistant:/config'
    dns:
      - 127.0.0.1
    devices:
      - /dev/ttyACM0:/dev/ttyACM0