version: '3.8'
services:
  homeassistant:
    image: homeassistant/home-assistant:stable
    container_name: home-assistant
    network_mode: host
    volumes:
      - ./services/home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
