- platform: miflora
  mac: !secret miflora_mac_1
  name: Pflanze 1
  monitored_conditions:
    - moisture
    - light
    - temperature
    - conductivity
    - battery

- platform: miflora
  mac: !secret miflora_mac_2
  name: Pflanze 2
  monitored_conditions:
    - moisture
    - light
    - temperature
    - conductivity
    - battery